### ISSUE TITLE
Missing prefix for functions and constants in the global namespace

### ISSUE THREAD

**Issue by mudrd8mz** [cbluesprl/moodle-local_quickregister#1]
Functions `encode_subscription_data()` and `decode_subscription_data()`  and the constant `TS_EXPIRY_AFTER` violate the naming guideline.

See https://docs.moodle.org/dev/Plugin_contribution_checklist#Namespace_collisions

**Comment by MallauryGerard** [comment]
Thank for your feedback. It has been fixed here : https://github.com/cbluesprl/moodle-local_quickregister/commit/89ab7589f884b46cae966680a60bee6fe18371c1
