### ISSUE TITLE
Performance: local_quickregister_before_http_headers could use $SCRIPT

### ISSUE THREAD

**Issue by mudrd8mz** [cbluesprl/moodle-local_quickregister#2]
These handlers could check the value of the `$SCRIPT` global and act only when

```
if ($SCRIPT === '/login/signup.php') {
     $subscription_data = optional_param('subscription_data', false, PARAM_RAW);
    // ...
}
```

That way, there will be no extra processing on _every_ page load just to support this.

**Comment by MallauryGerard** [comment]
Thank for your feedback. It has been fixed here : https://github.com/cbluesprl/moodle-local_quickregister/commit/89ab7589f884b46cae966680a60bee6fe18371c1
