### ISSUE TITLE
moodle_url does not need $CFG->wwwroot

### ISSUE THREAD

**Issue by mudrd8mz** [cbluesprl/moodle-local_quickregister#3]
One of the main benefits of using `moodle_url` is that it does not need to have `$CFG->wwwroot` - it uses it by default.

**Comment by MallauryGerard** [comment]
Thank for your feedback. It has been fixed here : https://github.com/cbluesprl/moodle-local_quickregister/commit/89ab7589f884b46cae966680a60bee6fe18371c1
